name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      # build wasm packages separately
      run: |
        go build `go list ./... | grep -v wasm`
        GOOS=js GOARCH=wasm go build `go list ./... | grep wasm`
    - name: Test
      run: go test ./...
    - name: Race Detector Test - memory # SQL test not passing
      run: go test github.com/elh/bitempura/memory -race
  golangci:
    name: lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33.0 # elh: my current version
          args: --timeout 5m
